steps:
  # Langkah untuk membangun Docker image dari folder yang diinginkan
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'cloud_computing/backend/Dockerfile'  # Tentukan path Dockerfile yang benar
      - '-t'
      - 'gcr.io/$PROJECT_ID/project-capstone-image'
      - '.'  # Konteks build adalah root repositori, gunakan path relatif yang sesuai

images:
  - 'gcr.io/$PROJECT_ID/project-capstone-image'
